name: Build Images

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

jobs:
  build-publish-image:
    name: Build Images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # node-rbenv
          - image: node-rbenv
            context: "16"
            tags: |
              kula/node-rbenv:16
              kula/node-rbenv:16.16
          - image: node-rbenv
            context: 16-slim
            tags: |
              kula/node-rbenv:16-slim
              kula/node-rbenv:16.16-slim
          - image: node-rbenv
            context: "18"
            tags: |
              kula/node-rbenv:18
              kula/node-rbenv:18.13
          - image: node-rbenv
            context: 18/ruby2.7.6
            tags: |
              kula/node-rbenv:18-ruby2.7.6
              kula/node-rbenv:18.13-ruby2.7.6
          - image: node-rbenv
            context: 18/ruby3.2.0
            tags: |
              kula/node-rbenv:18-ruby3.2.0
              kula/node-rbenv:18.13-ruby3.2.0
          - image: node-rbenv
            context: latest
            tags: |
              kula/node-rbenv:latest

          # node-ruby
          - image: node-ruby
            context: 18-3.2/alpine3.16
            tags: |
              kula/node-ruby:18-3.2-alpine3.16
              kula/node-ruby:18.13-3.2-alpine3.16

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: kula
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Image
        uses: docker/build-push-action@v3
        if: always()
        with:
          # cache-from: type=registry,ref=kula/${{ matrix.image }}:buildcache
          # cache-to: type=registry,ref=kula/${{ matrix.image }}:buildcache,mode=max
          context: images/${{ matrix.image }}/${{ matrix.context }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ matrix.tags }}
