name: Build Image

on:
  workflow_call:
    inputs:
      image:
        description: Image name (repository logical name)
        required: true
        type: string
      context:
        description: Build context path
        required: true
        type: string
      tags:
        description: Newline-separated list of tags to apply to the manifest
        required: true
        type: string
    secrets:
      DOCKERHUB_TOKEN:
        description: Docker Hub token
        required: true

permissions:
  contents: read
  packages: write

jobs:
  build-platform:
    name: "Build (${{ matrix.platform.name }})"
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: linux/amd64
            runner: ubuntu-24.04
            tag: linux-amd64
          - name: linux/arm64
            runner: ubuntu-24.04-arm
            tag: linux-arm64
    runs-on: ${{ matrix.platform.runner }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.context }}
          platforms: ${{ matrix.platform.name }}
          outputs: type=image,push-by-digest=true,name-canonical=true,push=${{ github.event_name != 'pull_request' }}

      - name: Export digest
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          set -e
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"
          ls -la /tmp/digests

      - name: Upload digest
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ inputs.image }}-${{ matrix.platform.tag }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  merge-manifests:
    name: Merge Manifests
    needs: build-platform
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download digests for image
        uses: actions/download-artifact@v5
        with:
          path: /tmp/digests
          pattern: digests-${{ inputs.image }}-*
          merge-multiple: true

      - name: Create and push multi-arch manifest
        if: ${{ github.event_name != 'pull_request' }}
        working-directory: /tmp/digests
        shell: bash
        run: |
          set -euo pipefail
          TAGS='${{ inputs.tags }}'
          if [ -z "$TAGS" ]; then
            echo "No tags provided for image, skipping" >&2
            exit 1
          fi
          image_tags=$(printf '%s' "$TAGS" | awk '{print "-t "$0}' | xargs)
          echo "Creating manifest list with tags: $image_tags"
          digest_refs=""
          while IFS= read -r tag; do
            repo=${tag%%:*}
            for f in *; do
              digest_refs="$digest_refs ${repo}@sha256:${f}"
            done
          done <<EOF
          $TAGS
          EOF
          echo "Digest references: $digest_refs"
          docker buildx imagetools create $image_tags $digest_refs
          first_tag=$(printf '%s' "$TAGS" | head -n1)
          docker buildx imagetools inspect "$first_tag"
