name: Build Images

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

jobs:
  build-publish-image:
    name: Build Images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # region node-rbenv

          # +===================+
          # | Image: node-rbenv |
          # +===================+

          # region Node.JS 16

          # +------------+
          # | Node.JS 16 |
          # +------------+
          - image: node-rbenv
            context: node-rbenv/node-16
            tags: |
              kula/node-rbenv:20
              kula/node-rbenv:20.1
              kula/node-rbenv:20.1.0

          # -- Ruby 2 --
          - image: node-rbenv
            context: node-rbenv/node-16/ruby-2
            tags: |
              kula/node-rbenv:20-ruby2
              kula/node-rbenv:20-ruby2.7
              kula/node-rbenv:20-ruby2.7.6
              kula/node-rbenv:20.1-ruby2
              kula/node-rbenv:20.1-ruby2.7
              kula/node-rbenv:20.1-ruby2.7.6
              kula/node-rbenv:20.1.0-ruby2
              kula/node-rbenv:20.1.0-ruby2.7
              kula/node-rbenv:20.1.0-ruby2.7.6

          # -- Ruby 3 --
          - image: node-rbenv
            context: node-rbenv/node-16/ruby-3
            tags: |
              kula/node-rbenv:20-ruby3
              kula/node-rbenv:20-ruby3.2
              kula/node-rbenv:20-ruby3.2.0
              kula/node-rbenv:20.1-ruby3
              kula/node-rbenv:20.1-ruby3.2
              kula/node-rbenv:20.1-ruby3.2.0
              kula/node-rbenv:20.1.0-ruby3
              kula/node-rbenv:20.1.0-ruby3.2
              kula/node-rbenv:20.1.0-ruby3.2.0

          #endregion
          # region Node.JS 16-slim

          # +-----------------+
          # | Node.JS 16-slim |
          # +-----------------+
          - image: node-rbenv
            context: node-rbenv/node-16-slim
            tags: |
              kula/node-rbenv:20-slim
              kula/node-rbenv:20.1-slim
              kula/node-rbenv:20.1.0-slim

          # -- Ruby 2 --
          - image: node-rbenv
            context: node-rbenv/node-16-slim/ruby-2
            tags: |
              kula/node-rbenv:20-slim-ruby2
              kula/node-rbenv:20-slim-ruby2.7
              kula/node-rbenv:20-slim-ruby2.7.6
              kula/node-rbenv:20.1-slim-ruby2
              kula/node-rbenv:20.1-slim-ruby2.7
              kula/node-rbenv:20.1-slim-ruby2.7.6
              kula/node-rbenv:20.1.0-slim-ruby2
              kula/node-rbenv:20.1.0-slim-ruby2.7
              kula/node-rbenv:20.1.0-slim-ruby2.7.6

          # -- Ruby 3 --
          - image: node-rbenv
            context: node-rbenv/node-16-slim/ruby-3
            tags: |
              kula/node-rbenv:20-slim-ruby3
              kula/node-rbenv:20-slim-ruby3.2
              kula/node-rbenv:20-slim-ruby3.2.0
              kula/node-rbenv:20.1-slim-ruby3
              kula/node-rbenv:20.1-slim-ruby3.2
              kula/node-rbenv:20.1-slim-ruby3.2.0
              kula/node-rbenv:20.1.0-slim-ruby3
              kula/node-rbenv:20.1.0-slim-ruby3.2
              kula/node-rbenv:20.1.0-slim-ruby3.2.0

          # endregion
          # region Node.JS 18

          # +------------+
          # | Node.JS 18 |
          # +------------+
          - image: node-rbenv
            context: node-rbenv/node-18
            tags: |
              kula/node-rbenv:20
              kula/node-rbenv:20.1
              kula/node-rbenv:20.1.0

          # -- Ruby 2 --
          - image: node-rbenv
            context: node-rbenv/node-18/ruby-2
            tags: |
              kula/node-rbenv:20-ruby2
              kula/node-rbenv:20.1-ruby2
              kula/node-rbenv:20.1.0-ruby2
              kula/node-rbenv:20-ruby2.7
              kula/node-rbenv:20.1-ruby2.7
              kula/node-rbenv:20.1.0-ruby2.7
              kula/node-rbenv:20-ruby2.7.6
              kula/node-rbenv:20.1-ruby2.7.6
              kula/node-rbenv:20.1.0-ruby2.7.6

          # -- Ruby 3 --
          - image: node-rbenv
            context: node-rbenv/node-18/ruby-3
            tags: |
              kula/node-rbenv:20-ruby3
              kula/node-rbenv:20.1-ruby3
              kula/node-rbenv:20.1.0-ruby3
              kula/node-rbenv:20-ruby3.2
              kula/node-rbenv:20.1-ruby3.2
              kula/node-rbenv:20.1.0-ruby3.2
              kula/node-rbenv:20-ruby3.2.0
              kula/node-rbenv:20.1-ruby3.2.0
              kula/node-rbenv:20.1.0-ruby3.2.0

          # endregion
          # region Node.JS 18-slim

          # +-----------------+
          # | Node.JS 18-slim |
          # +-----------------+
          - image: node-rbenv
            context: node-rbenv/node-18-slim
            tags: |
              kula/node-rbenv:20-slim
              kula/node-rbenv:20.1-slim
              kula/node-rbenv:20.1.0-slim

          # -- Ruby 2 --
          - image: node-rbenv
            context: node-rbenv/node-18-slim/ruby-2
            tags: |
              kula/node-rbenv:20-slim-ruby2
              kula/node-rbenv:20.1-slim-ruby2
              kula/node-rbenv:20.1.0-slim-ruby2
              kula/node-rbenv:20-slim-ruby2.7
              kula/node-rbenv:20.1-slim-ruby2.7
              kula/node-rbenv:20.1.0-slim-ruby2.7
              kula/node-rbenv:20-slim-ruby2.7.6
              kula/node-rbenv:20.1-slim-ruby2.7.6
              kula/node-rbenv:20.1.0-slim-ruby2.7.6

          # -- Ruby 3 --
          - image: node-rbenv
            context: node-rbenv/node-18-slim/ruby-3
            tags: |
              kula/node-rbenv:20-slim-ruby3
              kula/node-rbenv:20.1-slim-ruby3
              kula/node-rbenv:20.1.0-slim-ruby3
              kula/node-rbenv:20-slim-ruby3.2
              kula/node-rbenv:20.1-slim-ruby3.2
              kula/node-rbenv:20.1.0-slim-ruby3.2
              kula/node-rbenv:20-slim-ruby3.2.0
              kula/node-rbenv:20.1-slim-ruby3.2.0
              kula/node-rbenv:20.1.0-slim-ruby3.2.0

          # endregion
          # region Node.JS 20

          # +------------+
          # | Node.JS 20 |
          # +------------+
          - image: node-rbenv
            context: node-rbenv/node-20
            tags: |
              kula/node-rbenv:20
              kula/node-rbenv:20.1
              kula/node-rbenv:20.1.0

          # -- Ruby 2 --
          - image: node-rbenv
            context: node-rbenv/node-20/ruby-2
            tags: |
              kula/node-rbenv:20-ruby2
              kula/node-rbenv:20.1-ruby2
              kula/node-rbenv:20.1.0-ruby2
              kula/node-rbenv:20-ruby2.7
              kula/node-rbenv:20.1-ruby2.7
              kula/node-rbenv:20.1.0-ruby2.7
              kula/node-rbenv:20-ruby2.7.6
              kula/node-rbenv:20.1-ruby2.7.6
              kula/node-rbenv:20.1.0-ruby2.7.6

          # -- Ruby 3 --
          - image: node-rbenv
            context: node-rbenv/node-20/ruby-3
            tags: |
              kula/node-rbenv:20-ruby3
              kula/node-rbenv:20.1-ruby3
              kula/node-rbenv:20.1.0-ruby3
              kula/node-rbenv:20-ruby3.2
              kula/node-rbenv:20.1-ruby3.2
              kula/node-rbenv:20.1.0-ruby3.2
              kula/node-rbenv:20-ruby3.2.0
              kula/node-rbenv:20.1-ruby3.2.0
              kula/node-rbenv:20.1.0-ruby3.2.0

          # endregion
          # region Node.JS 20-slim

          # +-----------------+
          # | Node.JS 20-slim |
          # +-----------------+
          - image: node-rbenv
            context: node-rbenv/node-20-slim
            tags: |
              kula/node-rbenv:20-slim
              kula/node-rbenv:20.1-slim
              kula/node-rbenv:20.1.0-slim

          # -- Ruby 2 --
          - image: node-rbenv
            context: node-rbenv/node-20-slim/ruby-2
            tags: |
              kula/node-rbenv:20-slim-ruby2
              kula/node-rbenv:20.1-slim-ruby2
              kula/node-rbenv:20.1.0-slim-ruby2
              kula/node-rbenv:20-slim-ruby2.7
              kula/node-rbenv:20.1-slim-ruby2.7
              kula/node-rbenv:20.1.0-slim-ruby2.7
              kula/node-rbenv:20-slim-ruby2.7.6
              kula/node-rbenv:20.1-slim-ruby2.7.6
              kula/node-rbenv:20.1.0-slim-ruby2.7.6

          # -- Ruby 3 --
          - image: node-rbenv
            context: node-rbenv/node-20-slim/ruby-3
            tags: |
              kula/node-rbenv:20-slim-ruby3
              kula/node-rbenv:20.1-slim-ruby3
              kula/node-rbenv:20.1.0-slim-ruby3
              kula/node-rbenv:20-slim-ruby3.2
              kula/node-rbenv:20.1-slim-ruby3.2
              kula/node-rbenv:20.1.0-slim-ruby3.2
              kula/node-rbenv:20-slim-ruby3.2.0
              kula/node-rbenv:20.1-slim-ruby3.2.0
              kula/node-rbenv:20.1.0-slim-ruby3.2.0

          # endregion
          # region Node.JS Latest

          # +------------------+
          # | Node.JS - Latest |
          # +------------------+
          - image: node-rbenv
            context: node-rbenv/latest
            tags: |
              kula/node-rbenv:latest

          # endregion
          # endregion

          # region node-ruby
          # +==================+
          # | Image: node-ruby |
          # +==================+

          # +------------+
          # | Node.JS 18 |
          # +------------+

          # -- Ruby 2 --
          - image: node-ruby
            context: node-ruby/node-18/ruby-2/alpine3.16
            tags: |
              kula/node-ruby:18-ruby2-alpine3.16
              kula/node-ruby:18.20-ruby2-alpine3.16
              kula/node-ruby:18.20.0-ruby2-alpine3.16
              kula/node-ruby:18-ruby2.7-alpine3.16
              kula/node-ruby:18.20-ruby2.7-alpine3.16
              kula/node-ruby:18.20.0-ruby2.7-alpine3.16
              kula/node-ruby:18-ruby2.7.6-alpine3.16
              kula/node-ruby:18.20-ruby2.7.6-alpine3.16
              kula/node-ruby:18.20.0-ruby2.7.6-alpine3.16
          - image: node-ruby
            context: node-ruby/node-18/ruby-2/buster
            tags: |
              kula/node-ruby:18-ruby2-buster
              kula/node-ruby:18.20-ruby2-buster
              kula/node-ruby:18.20.0-ruby2-buster
              kula/node-ruby:18-ruby2.7-buster
              kula/node-ruby:18.20-ruby2.7-buster
              kula/node-ruby:18.20.0-ruby2.7-buster
              kula/node-ruby:18-ruby2.7.6-buster
              kula/node-ruby:18.20-ruby2.7.6-buster
              kula/node-ruby:18.20.0-ruby2.7.6-buster

          # -- Ruby 3 --
          - image: node-ruby
            context: node-ruby/18-3.2/alpine3.16
            tags: |
              kula/node-ruby:18-ruby3-alpine3.16
              kula/node-ruby:18.16-ruby3-alpine3.16
              kula/node-ruby:18.16.0-ruby3-alpine3.16
              kula/node-ruby:18-ruby3.2-alpine3.16
              kula/node-ruby:18.16-ruby3.2-alpine3.16
              kula/node-ruby:18.16.0-ruby3.2-alpine3.16
              kula/node-ruby:18-ruby3.2.0-alpine3.16
              kula/node-ruby:18.16-ruby3.2.0-alpine3.16
              kula/node-ruby:18.16.0-ruby3.2.0-alpine3.16
          - image: node-ruby
            context: node-ruby/node-18/ruby-3/buster
            tags: |
              kula/node-ruby:18-ruby3-buster
              kula/node-ruby:18.16-ruby3-buster
              kula/node-ruby:18.16.0-ruby3-buster
              kula/node-ruby:18-ruby3.2-buster
              kula/node-ruby:18.16-ruby3.2-buster
              kula/node-ruby:18.16.0-ruby3.2-buster
              kula/node-ruby:18-ruby3.2.0-buster
              kula/node-ruby:18.16-ruby3.2.0-buster
              kula/node-ruby:18.16.0-ruby3.2.0-buster

            # endregion

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: kula
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        uses: docker/build-push-action@v3
        if: always()
        with:
          cache-from: type=registry,ref=ghcr.io/kula-app/containers/${{ matrix.image }}:buildcache
          cache-to: type=registry,ref=ghcr.io/kula-app/containers/${{ matrix.image }}:buildcache,mode=max
          context: images/${{ matrix.context }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ matrix.tags }}
