name: Build Images

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Matrix
        id: matrix
        uses: actions/github-script@v8
        with:
          script: |
            const script = require('./bin/prepare-matrix.js')
            core.setOutput('matrix', script.generateMatrix())

  build-each-image:
    needs: generate-matrix
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    uses: ./.github/workflows/build-image.yml
    with:
      image: ${{ matrix.image.image }}
      context: ${{ matrix.image.context }}
      tags: ${{ matrix.image.tags }}
    secrets: inherit
