name: Build Images

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-publish-image:
    runs-on: ubuntu-latest
    name: "Build Images (${{ matrix.context}})"
    strategy:
      fail-fast: false
      matrix:
        include:
          # +------------+
          # | Node.JS 20 |
          # +------------+
          - image: node-rbenv
            context: node-rbenv/node-20
            tags: |
              kula/node-rbenv:20
              kula/node-rbenv:20.19
              kula/node-rbenv:20.19.5

          # -- Ruby 3 --
          - image: node-rbenv
            context: node-rbenv/node-20/ruby-3
            tags: |
              kula/node-rbenv:20-ruby3
              kula/node-rbenv:20.19-ruby3
              kula/node-rbenv:20.19.5-ruby3
              kula/node-rbenv:20-ruby3.4
              kula/node-rbenv:20.19-ruby3.4
              kula/node-rbenv:20.19.5-ruby3.4
              kula/node-rbenv:20-ruby3.4.5
              kula/node-rbenv:20.19-ruby3.4.5
              kula/node-rbenv:20.19.5-ruby3.4.5

          # +-----------------+
          # | Node.JS 20-slim |
          # +-----------------+
          - image: node-rbenv
            context: node-rbenv/node-20-slim
            tags: |
              kula/node-rbenv:20-slim
              kula/node-rbenv:20.19-slim
              kula/node-rbenv:20.19.5-slim

          # -- Ruby 3 --
          - image: node-rbenv
            context: node-rbenv/node-20-slim/ruby-3
            tags: |
              kula/node-rbenv:20-slim-ruby3
              kula/node-rbenv:20.19-slim-ruby3
              kula/node-rbenv:20.19.5-slim-ruby3
              kula/node-rbenv:20-slim-ruby3.4
              kula/node-rbenv:20.19-slim-ruby3.4
              kula/node-rbenv:20.19.5-slim-ruby3.4
              kula/node-rbenv:20-slim-ruby3.4.5
              kula/node-rbenv:20.19-slim-ruby3.4.5
              kula/node-rbenv:20.19.5-slim-ruby3.4.5

          # +------------------+
          # | Node.JS - Latest |
          # +------------------+
          - image: node-rbenv
            context: node-rbenv/node-latest
            tags: |
              kula/node-rbenv:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: kula
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        uses: docker/build-push-action@v5
        if: always()
        with:
          cache-from: type=registry,ref=ghcr.io/kula-app/containers/${{ matrix.image }}:buildcache
          cache-to: type=registry,ref=ghcr.io/kula-app/containers/${{ matrix.image }}:buildcache,mode=max
          context: images/${{ matrix.context }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ matrix.tags }}
