name: Build Images

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-matrix:
    name: Generate Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Generate Matrix
        id: matrix
        uses: actions/github-script@v8
        with:
          script: |
            const script = require('./bin/prepare-matrix.js')
            core.setOutput('matrix', script.generateMatrix())

  build-each-image:
    name: Build Image (${{ matrix.image.context }})
    needs: generate-matrix
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    uses: ./.github/workflows/build-image.yml
    with:
      id: ${{ matrix.image.id }}
      image: ${{ matrix.image.image }}
      context: ${{ matrix.image.context }}
      tags: ${{ matrix.image.tags }}
    secrets: inherit

  required-check:
    needs: [generate-matrix, build-each-image]
    name: Build Images
    # This is necessary since a failed/skipped dependent job would cause this job to be skipped
    if: always()
    runs-on: ubuntu-latest
    steps:
      # If any jobs we depend on fails gets cancelled or times out, this job will fail.
      # Skipped jobs are not considered failures.
      - name: Check for failures
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: |
          echo "One of the build jobs has failed." && exit 1
