name: Build Images

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-publish-image:
    name: Build Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build node-rbenv 16
        uses: docker/build-push-action@v3
        with:
          cache-from: type=registry,ref=ghcr.io/kula-app/containers/node-rbenv:buildcache
          cache-to: type=registry,ref=ghcr.io/kula-app/containers/node-rbenv:buildcache,mode=max
          context: images/node-rbenv/16
          labels: kula/node-rbenv
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            latest
            16
            16.16

      - name: Build node-rbenv 16-slim
        uses: docker/build-push-action@v3
        with:
          cache-from: type=registry,ref=ghcr.io/kula-app/containers/node-rbenv:buildcache
          cache-to: type=registry,ref=ghcr.io/kula-app/containers/node-rbenv:buildcache,mode=max
          context: images/node-rbenv/16
          labels: kula/node-rbenv
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            16-slim
            16.16-slim

      - name: Build node-ruby 18-3.2-alpine3.16
        uses: docker/build-push-action@v3
        with:
          cache-from: type=registry,ref=ghcr.io/kula-app/containers/node-ruby:buildcache
          cache-to: type=registry,ref=ghcr.io/kula-app/containers/node-ruby:buildcache,mode=max
          context: images/node-ruby/18-3.2/alpine3.16
          labels: kula/node-ruby
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            latest
            18-3.2-alpine3.16
            18.13-3.2-alpine3.16
